# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/kmol/桌面/Pyquino_plugin/vrep_pypot/vrep_pypot.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 730)
        MainWindow.setMinimumSize(QtCore.QSize(621, 730))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.mainLayout.setObjectName("mainLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addMachineVrep = QtWidgets.QPushButton(self.centralWidget)
        self.addMachineVrep.setObjectName("addMachineVrep")
        self.verticalLayout.addWidget(self.addMachineVrep)
        self.motors = QtWidgets.QPushButton(self.centralWidget)
        self.motors.setObjectName("motors")
        self.verticalLayout.addWidget(self.motors)
        self.addMachine = QtWidgets.QPushButton(self.centralWidget)
        self.addMachine.setObjectName("addMachine")
        self.verticalLayout.addWidget(self.addMachine)
        self.restart = QtWidgets.QPushButton(self.centralWidget)
        self.restart.setObjectName("restart")
        self.verticalLayout.addWidget(self.restart)
        self.simraution = QtWidgets.QPushButton(self.centralWidget)
        self.simraution.setObjectName("simraution")
        self.verticalLayout.addWidget(self.simraution)
        self.motorname = QtWidgets.QComboBox(self.centralWidget)
        self.motorname.setObjectName("motorname")
        self.verticalLayout.addWidget(self.motorname)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.motorTable = QtWidgets.QTableWidget(self.centralWidget)
        self.motorTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.motorTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.motorTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.motorTable.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.motorTable.setObjectName("motorTable")
        self.motorTable.setColumnCount(5)
        self.motorTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.motorTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.motorTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.motorTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.motorTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.motorTable.setHorizontalHeaderItem(4, item)
        self.motorTable.horizontalHeader().setDefaultSectionSize(75)
        self.motorTable.horizontalHeader().setMinimumSectionSize(75)
        self.horizontalLayout.addWidget(self.motorTable)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.updataButton = QtWidgets.QPushButton(self.centralWidget)
        self.updataButton.setObjectName("updataButton")
        self.verticalLayout_4.addWidget(self.updataButton)
        self.xAxisleft = QtWidgets.QPushButton(self.centralWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Pyquino/core/icon/arrow-left-b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.xAxisleft.setIcon(icon)
        self.xAxisleft.setIconSize(QtCore.QSize(30, 30))
        self.xAxisleft.setObjectName("xAxisleft")
        self.verticalLayout_4.addWidget(self.xAxisleft)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.xAxisrigh = QtWidgets.QPushButton(self.centralWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Pyquino/core/icon/arrow-right-b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.xAxisrigh.setIcon(icon1)
        self.xAxisrigh.setIconSize(QtCore.QSize(30, 30))
        self.xAxisrigh.setObjectName("xAxisrigh")
        self.verticalLayout_4.addWidget(self.xAxisrigh)
        self.yAxisup = QtWidgets.QPushButton(self.centralWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Pyquino/core/icon/arrow-up-b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.yAxisup.setIcon(icon2)
        self.yAxisup.setIconSize(QtCore.QSize(30, 30))
        self.yAxisup.setObjectName("yAxisup")
        self.verticalLayout_4.addWidget(self.yAxisup)
        self.yAxisdown = QtWidgets.QPushButton(self.centralWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../Pyquino/core/icon/arrow-down-b.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.yAxisdown.setIcon(icon3)
        self.yAxisdown.setIconSize(QtCore.QSize(30, 30))
        self.yAxisdown.setObjectName("yAxisdown")
        self.verticalLayout_4.addWidget(self.yAxisdown)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.mainLayout.addLayout(self.horizontalLayout)
        self.reciver = QtWidgets.QTextEdit(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reciver.sizePolicy().hasHeightForWidth())
        self.reciver.setSizePolicy(sizePolicy)
        self.reciver.setObjectName("reciver")
        self.mainLayout.addWidget(self.reciver)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 621, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuOpenfile = QtWidgets.QMenu(self.menuBar)
        self.menuOpenfile.setObjectName("menuOpenfile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuOpenfile.addAction(self.actionOpen)
        self.menuBar.addAction(self.menuOpenfile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addMachineVrep.setText(_translate("MainWindow", "AddMachine"))
        self.motors.setText(_translate("MainWindow", "motors"))
        self.addMachine.setText(_translate("MainWindow", "add_machine"))
        self.restart.setText(_translate("MainWindow", "restart_simulation"))
        self.simraution.setText(_translate("MainWindow", "stop_simuration"))
        item = self.motorTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.motorTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.motorTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Position"))
        item = self.motorTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Limitation"))
        item = self.motorTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Force"))
        self.updataButton.setText(_translate("MainWindow", "Send"))
        self.xAxisleft.setText(_translate("MainWindow", "getforce"))
        self.xAxisrigh.setText(_translate("MainWindow", "right"))
        self.yAxisup.setText(_translate("MainWindow", "up"))
        self.yAxisdown.setText(_translate("MainWindow", "back"))
        self.menuOpenfile.setTitle(_translate("MainWindow", "file"))
        self.actionOpen.setText(_translate("MainWindow", "open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

